### ISSUE TITLE
Consider including Alpha and Beta labels to API versions

### ISSUE THREAD

**Issue by RandyLevensalor** [camaraproject/ReleaseManagement#13]
**Problem description**
Pre 1.0.0 api are generally being considered to be either beta or alpha and are unstable.  With new releases that be break compatibility.  As mentioned during the recent governing committee call, all of these pre 1.0.0 APIs would be accesses as a v0 API.  And per the commonalities guideline, all v0 API calls should be backwards compatibility.

**Possible evolution**
Add an Alpha or Beta prefix to pre-released APIs and then increment the release version when backwards compatibility is broken.

So you could have v1Alpha1 and v1Alpha2, v1Beta1, v1BetaN..., v1 to indicate incompatible releases.

This could follow a similar api versioning rules to Kubernetes.  https://kubernetes.io/docs/reference/using-api/#api-versioning

A release could begin with the following:

```yaml
version: 1Alpha0.0.0
...
      basePath:
        default: endpoint/v1Alpha0
```

Updates which don't break backwards compatibility would update the minor and patch version without changing the default `basePath`.

Subsequent alpha releases which break backwards compatibility would update the major version and default `basePath`

```yaml
version: 1Alpha1.0.0
...
      basePath:
        default: endpoint/v1Alpha1
```

Once the API is stable and ready for beta, the major release would move to beta.

```yaml
version: 1Beta0.0.0
...
      basePath:
        default: endpoint/v1Beta0
```

Once the API is stable and ready to be released, the beta would be removed from the versioning.

```yaml
version: 1.0.0
...
      basePath:
        default: endpoint/v1
```

If there is a need for a second release of the API, the alpha and beta process would start again.

**Alternative solution**
Move to new major releases when API backwards compatibility is broken.  However, this could lead to 1.0.0, 2.0.0 and later releases that are beta and alpha, which could be confusing. 

**Additional context**
Many of the CAMARA APIs are undergoing several iterations before being becoming stable enough to be released and the versioning could be extended to align with this process.

[Semantic Versioning](https://semver.org/) is a well established process, but hasn't updated to reflect cloud native and web development.  Especially since the full version string is not a part of api path.  When semantic versioning is used for packages and libraries, there are capabilities to include both minor and patch version.  This convention of supporting minor and patch versions in endpoints, in addition to the base endpoint based on the major version isn't common with restful interfaces.
