### ISSUE TITLE
Add guidance for Info object in apis

### ISSUE THREAD

**Issue by RandyLevensalor** [camaraproject/ReleaseManagement#15]
[OpenAPI Info Object](https://spec.openapis.org/oas/v3.0.3#info-object)

Provide guidance on the info-object.  For instance the following fields could have consistency.

```yaml
  termsOfService: http://swagger.io/terms/
  contact:
    email: project-email@sample.com
```
