### ISSUE TITLE
Remove basePath in servers.url as variable

### ISSUE THREAD

**Issue by jlurien** [camaraproject/ReleaseManagement#17]
**Problem description**
I noticed that we are misusing variables in servers.url properties in most API definitions.

Commonly we define `servers` as, e.g.:

```
servers:
  - url: "{apiRoot}/{basePath}"
    variables:
      apiRoot:
        default: http://localhost:9091
        description: API root
      basePath:
        default: qod/v0
        description: Base path for the QoD API
```

But `basePath` which is the api-name and major version is not something that may be changed by the client. `default` is defined in OAS as:

| Field Name | Type | Description |
| --|:---:|---|
| default	| string |	**REQUIRED**. The default value to use for substitution, and to send, if an alternate value is not supplied. Unlike the Schema Object's `default`, this value MUST be provided by the consumer. |

We are not allowing an alternate value to be supplied by the API client, so this part of the `servers.url` must be fixed. 

**Possible evolution**
Proposal is to redefine `servers` as, e.g.:

```
servers:
  - url: "{apiRoot}/qod/v0"
    variables:
      apiRoot:
        default: http://localhost:9091
        description: API root
```

**Comment by tanjadegroot** [comment]
The proposed closure is to 
1) add @jlurien proposed servers definition to the API guidelines in commonalities as per above:

```
servers:
  - url: "{apiRoot}/qod/v0"
    variables:
      apiRoot:
        default: http://localhost:9091
        description: API root
```

2) Have a CAMARA specific exception for initial public-release APIs with API version with x=0 which may have v0.y in the base path.
It should be understood that any v0 API has a risk to change !

example 
```
servers:
  - url: "{apiRoot}/qod/v0.10"
```

This is described in the API versioning here: [API versioning](https://wiki.camaraproject.org/x/a4BaAQ)

With that I think this issue can be transferred back to Commonalities to update the API guidelines with the above information.
